/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "packet.pb-c.h"
void   packet__init
                     (Packet         *message)
{
  static Packet init_value = PACKET__INIT;
  *message = init_value;
}
size_t packet__get_packed_size
                     (const Packet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet__pack
                     (const Packet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet__pack_to_buffer
                     (const Packet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Packet *
       packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Packet *)
     protobuf_c_message_unpack (&packet__descriptor,
                                allocator, len, data);
}
void   packet__free_unpacked
                     (Packet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packet__field_descriptors[2] =
{
  {
    "seq_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Packet, seq_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Packet, payload),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet__field_indices_by_name[] = {
  1,   /* field[1] = payload */
  0,   /* field[0] = seq_num */
};
static const ProtobufCIntRange packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor packet__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Packet",
  "Packet",
  "Packet",
  "",
  sizeof(Packet),
  2,
  packet__field_descriptors,
  packet__field_indices_by_name,
  1,  packet__number_ranges,
  (ProtobufCMessageInit) packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
