/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_protobuf_2drpc_2eproto__INCLUDED
#define PROTOBUF_C_protobuf_2drpc_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ConnectInfoT ConnectInfoT;


/* --- enums --- */


/* --- messages --- */

struct  _ConnectInfoT
{
  ProtobufCMessage base;
  char *connectip;
  int32_t port;
};
#define CONNECT_INFO_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connect_info_t__descriptor) \
    , NULL, 0 }


/* ConnectInfoT methods */
void   connect_info_t__init
                     (ConnectInfoT         *message);
size_t connect_info_t__get_packed_size
                     (const ConnectInfoT   *message);
size_t connect_info_t__pack
                     (const ConnectInfoT   *message,
                      uint8_t             *out);
size_t connect_info_t__pack_to_buffer
                     (const ConnectInfoT   *message,
                      ProtobufCBuffer     *buffer);
ConnectInfoT *
       connect_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connect_info_t__free_unpacked
                     (ConnectInfoT *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ConnectInfoT_Closure)
                 (const ConnectInfoT *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor connect_info_t__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_protobuf_2drpc_2eproto__INCLUDED */
