/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "protobuf-rpc.pb-c.h"
void   connect_info_t__init
                     (ConnectInfoT         *message)
{
  static ConnectInfoT init_value = CONNECT_INFO_T__INIT;
  *message = init_value;
}
size_t connect_info_t__get_packed_size
                     (const ConnectInfoT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &connect_info_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect_info_t__pack
                     (const ConnectInfoT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &connect_info_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect_info_t__pack_to_buffer
                     (const ConnectInfoT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &connect_info_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectInfoT *
       connect_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectInfoT *)
     protobuf_c_message_unpack (&connect_info_t__descriptor,
                                allocator, len, data);
}
void   connect_info_t__free_unpacked
                     (ConnectInfoT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &connect_info_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor connect_info_t__field_descriptors[2] =
{
  {
    "connectIP",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ConnectInfoT, connectip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ConnectInfoT, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect_info_t__field_indices_by_name[] = {
  0,   /* field[0] = connectIP */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange connect_info_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor connect_info_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "connect_info_t",
  "ConnectInfoT",
  "ConnectInfoT",
  "",
  sizeof(ConnectInfoT),
  2,
  connect_info_t__field_descriptors,
  connect_info_t__field_indices_by_name,
  1,  connect_info_t__number_ranges,
  (ProtobufCMessageInit) connect_info_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
